/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sunrise.dental.view;

/**
 *
 * @author Danidu
 */
public class BillingForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BillingForm.class.getName());
    
    private void clearBillDetails() {

    txtPatientName.setText("");
    txtTreatmentType.setText("");
    txtTreatmentCost.setText("");
    txtConsultationFee.setText("");
    txtTotalAmount.setText("");
    txtBillDate.setText("");
}
    
    private String getJsonValue(String json, String key) {

    String pattern = "\"" + key + "\":\"";

    int start = json.indexOf(pattern);

    if (start == -1) {
        return "";
    }

    start += pattern.length();

    int end = json.indexOf("\"", start);

    if (end == -1) {
        return "";
    }

    return json.substring(start, end);
}

    /**
     * Creates new form BillingForm
     */
    public BillingForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAppointmentNo = new javax.swing.JTextField();
        txtPatientName = new javax.swing.JTextField();
        txtTreatmentType = new javax.swing.JTextField();
        txtTreatmentCost = new javax.swing.JTextField();
        txtConsultationFee = new javax.swing.JTextField();
        txtTotalAmount = new javax.swing.JTextField();
        txtBillDate = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Appointment Number");

        jLabel2.setText("Patient Name");

        jLabel3.setText("Treatment Type");

        jLabel4.setText("Treatment Cost");

        jLabel5.setText("Consultation Fee");

        jLabel6.setText("Total Amount");

        jLabel7.setText("Bill Date");

        txtAppointmentNo.addActionListener(this::txtAppointmentNoActionPerformed);

        txtPatientName.setEditable(false);

        txtTreatmentType.setEditable(false);

        btnCalculate.setText("Calculate Bill");
        btnCalculate.addActionListener(this::btnCalculateActionPerformed);

        btnPrint.setText("Print Receipt");
        btnPrint.addActionListener(this::btnPrintActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCalculate)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAppointmentNo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTreatmentType, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTreatmentCost, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConsultationFee, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBillDate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnPrint)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(btnBack)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAppointmentNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTreatmentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTreatmentCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtConsultationFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtBillDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalculate)
                    .addComponent(btnPrint)
                    .addComponent(btnClear)
                    .addComponent(btnBack))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAppointmentNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAppointmentNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAppointmentNoActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
String appointmentNo = txtAppointmentNo.getText().trim();

if (appointmentNo.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Please enter appointment number."
    );
    txtAppointmentNo.requestFocus();
    return;
}

try {

    String encodedNo = java.net.URLEncoder.encode(
            appointmentNo,
            java.nio.charset.StandardCharsets.UTF_8
    );

    java.net.URL url = new java.net.URL(
            "http://localhost:8080/api/billing/calculate"
            + "?appointmentNo="
            + encodedNo
    );

    java.net.HttpURLConnection connection =
            (java.net.HttpURLConnection) url.openConnection();

    connection.setRequestMethod("GET");

    int responseCode = connection.getResponseCode();

    java.io.InputStream stream;

    if (responseCode >= 200 && responseCode < 300) {
        stream = connection.getInputStream();
    } else {
        stream = connection.getErrorStream();
    }

    java.util.Scanner scanner =
            new java.util.Scanner(stream);

    StringBuilder response =
            new StringBuilder();

    while (scanner.hasNextLine()) {
        response.append(scanner.nextLine());
    }

    scanner.close();

    String responseText = response.toString();

    if (responseCode == 200) {

        txtPatientName.setText(
                getJsonValue(responseText, "patientName")
        );

        txtTreatmentType.setText(
                getJsonValue(responseText, "treatmentType")
        );

        txtTreatmentCost.setText(
                getJsonValue(responseText, "treatmentCost")
        );

        txtConsultationFee.setText(
                getJsonValue(responseText, "consultationFee")
        );

        txtTotalAmount.setText(
                getJsonValue(responseText, "totalAmount")
        );

        txtBillDate.setText(
                getJsonValue(responseText, "billDate")
        );

    } else {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Appointment not found."
        );

        clearBillDetails();
    }

    connection.disconnect();

} catch (Exception e) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Unable to connect to the server."
    );

    e.printStackTrace();
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
txtAppointmentNo.setText("");
clearBillDetails();
txtAppointmentNo.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
MainMenuForm mainMenu = new MainMenuForm();
mainMenu.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
String receipt =
        "SUNRISE DENTAL CLINIC\n\n"
        + "Appointment No: " + txtAppointmentNo.getText() + "\n"
        + "Patient Name: " + txtPatientName.getText() + "\n"
        + "Treatment: " + txtTreatmentType.getText() + "\n"
        + "Treatment Cost: Rs. " + txtTreatmentCost.getText() + "\n"
        + "Consultation Fee: Rs. " + txtConsultationFee.getText() + "\n"
        + "Total Amount: Rs. " + txtTotalAmount.getText() + "\n"
        + "Bill Date: " + txtBillDate.getText() + "\n";

javax.swing.JTextArea printArea =
        new javax.swing.JTextArea(receipt);

try {

    boolean printed = printArea.print();

    if (printed) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Receipt sent to printer."
        );
    }

} catch (java.awt.print.PrinterException e) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Unable to print receipt."
    );
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BillingForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAppointmentNo;
    private javax.swing.JTextField txtBillDate;
    private javax.swing.JTextField txtConsultationFee;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtTotalAmount;
    private javax.swing.JTextField txtTreatmentCost;
    private javax.swing.JTextField txtTreatmentType;
    // End of variables declaration//GEN-END:variables
}
