/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sunrise.dental.view;

/**
 *
 * @author Danidu
 */
public class MainMenuForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenuForm.class.getName());

    /**
     * Creates new form MainMenuForm
     */
    public MainMenuForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRegisterAppointment = new javax.swing.JButton();
        btnSearchAppointment = new javax.swing.JButton();
        btnBilling = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sunrise Dental Clinic Appointment and Patient Management System");

        btnRegisterAppointment.setText("Register Appointment");
        btnRegisterAppointment.addActionListener(this::btnRegisterAppointmentActionPerformed);

        btnSearchAppointment.setText("Search Appointment");
        btnSearchAppointment.addActionListener(this::btnSearchAppointmentActionPerformed);

        btnBilling.setText("Calculate / Print Bill");
        btnBilling.addActionListener(this::btnBillingActionPerformed);

        btnReports.setText("Reports");

        btnHelp.setText("Help");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        btnExit.setText("Exit");
        btnExit.addActionListener(this::btnExitActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit)
                    .addComponent(btnLogout)
                    .addComponent(btnHelp)
                    .addComponent(btnReports)
                    .addComponent(btnBilling)
                    .addComponent(btnRegisterAppointment)
                    .addComponent(btnSearchAppointment))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(btnRegisterAppointment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchAppointment)
                .addGap(18, 18, 18)
                .addComponent(btnBilling)
                .addGap(18, 18, 18)
                .addComponent(btnReports)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
LoginForm loginForm = new LoginForm();
loginForm.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
int response = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to exit?",
        "Exit",
        javax.swing.JOptionPane.YES_NO_OPTION
);

if (response == javax.swing.JOptionPane.YES_OPTION) {
    System.exit(0);
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnRegisterAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterAppointmentActionPerformed
RegisterAppointmentForm form =
        new RegisterAppointmentForm();

form.setVisible(true);

this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterAppointmentActionPerformed

    private void btnSearchAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAppointmentActionPerformed
SearchAppointmentForm searchForm =
        new SearchAppointmentForm();

searchForm.setVisible(true);

this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchAppointmentActionPerformed

    private void btnBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillingActionPerformed
BillingForm billingForm = new BillingForm();
billingForm.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBillingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainMenuForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBilling;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRegisterAppointment;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnSearchAppointment;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
