/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sunrise.dental.view;

/**
 *
 * @author Danidu
 */
public class RegisterAppointmentForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterAppointmentForm.class.getName());

    /**
     * Creates new form RegisterAppointmentForm
     */
    public RegisterAppointmentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAppointmentNo = new javax.swing.JTextField();
        txtPatientName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtContactNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbDentist = new javax.swing.JComboBox<>();
        cmbTreatment = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAppointmentTime = new javax.swing.JTextField();
        txtAppointmentDate = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Register New Appointment");

        txtAppointmentNo.setText("jTextField1");

        txtPatientName.setText("jTextField2");

        txtAddress.setText("jTextField3");

        txtContactNumber.setText("jTextField4");

        jLabel2.setText("Appointment Number");

        jLabel3.setText("Patient Name");

        jLabel4.setText("Address");

        jLabel5.setText("Contact Number");

        cmbDentist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Dentist", "Dr. Silva", "Dr. Perera", "Dr. Fernando" }));
        cmbDentist.addActionListener(this::cmbDentistActionPerformed);

        cmbTreatment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Treatment", "Dental Cleaning", "Dental Filling", "Tooth Extraction", "Root Canal Treatment" }));

        jLabel6.setText("Dentist Name");

        jLabel7.setText("Treatment Type");

        jLabel8.setText("Appointment Date");

        jLabel9.setText("Appointment Time");

        txtAppointmentTime.setText("HH:mm");

        txtAppointmentDate.setText("YYYY-MM-DD");
        txtAppointmentDate.addActionListener(this::txtAppointmentDateActionPerformed);

        btnRegister.setText("Register");
        btnRegister.addActionListener(this::btnRegisterActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(79, 79, 79)
                                .addComponent(txtAppointmentTime, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addGap(54, 54, 54)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPatientName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAppointmentNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(btnRegister)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(btnClear)
                                        .addGap(47, 47, 47)
                                        .addComponent(btnBack))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addComponent(txtAppointmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(100, 100, 100)
                                .addComponent(cmbDentist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(90, 90, 90)
                                .addComponent(cmbTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAppointmentNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(cmbDentist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtAppointmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtAppointmentTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(btnClear)
                    .addComponent(btnBack))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbDentistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDentistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDentistActionPerformed

    private void txtAppointmentDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAppointmentDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAppointmentDateActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
String appointmentNo = txtAppointmentNo.getText().trim();
String patientName = txtPatientName.getText().trim();
String address = txtAddress.getText().trim();
String contactNumber = txtContactNumber.getText().trim();

String dentistName =
        cmbDentist.getSelectedItem().toString();

String treatmentName =
        cmbTreatment.getSelectedItem().toString();

String appointmentDate =
        txtAppointmentDate.getText().trim();

String appointmentTime =
        txtAppointmentTime.getText().trim();

if (appointmentNo.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Please enter appointment number."
    );
    txtAppointmentNo.requestFocus();
    return;
}

if (patientName.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Please enter patient name."
    );
    txtPatientName.requestFocus();
    return;
}

if (!patientName.matches("[a-zA-Z ]+")) {
    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Patient name should contain only letters."
    );
    txtPatientName.requestFocus();
    return;
}

if (address.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Please enter address."
    );
    txtAddress.requestFocus();
    return;
}

if (contactNumber.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Please enter contact number."
    );
    txtContactNumber.requestFocus();
    return;
}

if (!contactNumber.matches("\\d{10}")) {
    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Contact number must contain 10 digits."
    );
    txtContactNumber.requestFocus();
    return;
}

if (cmbDentist.getSelectedIndex() == 0) {
    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Please select a dentist."
    );
    return;
}

if (cmbTreatment.getSelectedIndex() == 0) {
    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Please select a treatment."
    );
    return;
}

if (appointmentDate.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Please enter appointment date."
    );
    return;
}

if (appointmentTime.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Please enter appointment time."
    );
    return;
}  
int treatmentId = 0;

switch (cmbTreatment.getSelectedIndex()) {

    case 1:
        treatmentId = 1;
        break;

    case 2:
        treatmentId = 2;
        break;

    case 3:
        treatmentId = 3;
        break;

    case 4:
        treatmentId = 4;
        break;
}try {

    java.net.URL url =
            new java.net.URL(
                    "http://localhost:8080/api/appointments/register"
            );

    java.net.HttpURLConnection connection =
            (java.net.HttpURLConnection) url.openConnection();

    connection.setRequestMethod("POST");
    connection.setDoOutput(true);

    connection.setRequestProperty(
            "Content-Type",
            "application/x-www-form-urlencoded"
    );

    String data =
            "appointmentNo="
            + java.net.URLEncoder.encode(
                    appointmentNo,
                    java.nio.charset.StandardCharsets.UTF_8
            )
            + "&patientName="
            + java.net.URLEncoder.encode(
                    patientName,
                    java.nio.charset.StandardCharsets.UTF_8
            )
            + "&address="
            + java.net.URLEncoder.encode(
                    address,
                    java.nio.charset.StandardCharsets.UTF_8
            )
            + "&contactNumber="
            + java.net.URLEncoder.encode(
                    contactNumber,
                    java.nio.charset.StandardCharsets.UTF_8
            )
            + "&dentistName="
            + java.net.URLEncoder.encode(
                    dentistName,
                    java.nio.charset.StandardCharsets.UTF_8
            )
            + "&treatmentId="
            + treatmentId
            + "&appointmentDate="
            + java.net.URLEncoder.encode(
                    appointmentDate,
                    java.nio.charset.StandardCharsets.UTF_8
            )
            + "&appointmentTime="
            + java.net.URLEncoder.encode(
                    appointmentTime,
                    java.nio.charset.StandardCharsets.UTF_8
            );

    try (java.io.OutputStream os =
                 connection.getOutputStream()) {

        os.write(
                data.getBytes(
                        java.nio.charset.StandardCharsets.UTF_8
                )
        );
    }

    int responseCode =
            connection.getResponseCode();

    java.io.InputStream inputStream;

    if (responseCode >= 200 && responseCode < 300) {

        inputStream = connection.getInputStream();

    } else {

        inputStream = connection.getErrorStream();
    }

    java.util.Scanner scanner =
            new java.util.Scanner(inputStream);

    StringBuilder response =
            new StringBuilder();

    while (scanner.hasNextLine()) {
        response.append(scanner.nextLine());
    }

    scanner.close();

    if (responseCode == 200) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Appointment registered successfully."
        );

        clearForm();

    } else {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                response.toString()
        );
    }

} catch (Exception e) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Unable to connect to the server."
    );

    e.printStackTrace();
}
    }//GEN-LAST:event_btnRegisterActionPerformed
private void clearForm() {

    txtAppointmentNo.setText("");
    txtPatientName.setText("");
    txtAddress.setText("");
    txtContactNumber.setText("");

    cmbDentist.setSelectedIndex(0);
    cmbTreatment.setSelectedIndex(0);

    txtAppointmentDate.setText("");
    txtAppointmentTime.setText("");

    txtAppointmentNo.requestFocus();
}
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
clearForm();        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
MainMenuForm mainMenu = new MainMenuForm();

mainMenu.setVisible(true);

this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegisterAppointmentForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<String> cmbDentist;
    private javax.swing.JComboBox<String> cmbTreatment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAppointmentDate;
    private javax.swing.JTextField txtAppointmentNo;
    private javax.swing.JTextField txtAppointmentTime;
    private javax.swing.JTextField txtContactNumber;
    private javax.swing.JTextField txtPatientName;
    // End of variables declaration//GEN-END:variables
}
