/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sunrise.dental.view;

/**
 *
 * @author Danidu
 */
public class ReportsForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportsForm.class.getName());

    /**
     * Creates new form ReportsForm
     */
    public ReportsForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtReportDate = new javax.swing.JTextField();
        btnAppointmentsByDate = new javax.swing.JButton();
        btnTreatmentSummary = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReports = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Clinic Reports");

        jLabel2.setText("Appointment Date");

        txtReportDate.addActionListener(this::txtReportDateActionPerformed);

        btnAppointmentsByDate.setText("Appointments By Date");
        btnAppointmentsByDate.addActionListener(this::btnAppointmentsByDateActionPerformed);

        btnTreatmentSummary.setText("Treatment Summary");
        btnTreatmentSummary.addActionListener(this::btnTreatmentSummaryActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        tblReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblReports);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnAppointmentsByDate)
                        .addGap(40, 40, 40)
                        .addComponent(btnTreatmentSummary)
                        .addGap(38, 38, 38)
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel2)
                                .addGap(41, 41, 41)
                                .addComponent(txtReportDate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtReportDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAppointmentsByDate)
                    .addComponent(btnTreatmentSummary)
                    .addComponent(btnClear)
                    .addComponent(btnBack))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtReportDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReportDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReportDateActionPerformed

    private void btnAppointmentsByDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointmentsByDateActionPerformed
String date =
        txtReportDate.getText().trim();

if (date.isEmpty()) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Please enter appointment date."
    );

    return;
}

try {

    String encodedDate =
            java.net.URLEncoder.encode(
                    date,
                    java.nio.charset.StandardCharsets.UTF_8
            );

    java.net.URL url =
            new java.net.URL(
                    "http://localhost:8080"
                    + "/api/reports/appointments-by-date"
                    + "?date="
                    + encodedDate
            );

    java.net.HttpURLConnection connection =
            (java.net.HttpURLConnection)
                    url.openConnection();

    connection.setRequestMethod("GET");

    int responseCode =
            connection.getResponseCode();

    if (responseCode != 200) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Invalid date."
        );

        return;
    }

    java.util.Scanner scanner =
            new java.util.Scanner(
                    connection.getInputStream()
            );

    javax.swing.table.DefaultTableModel model =
            new javax.swing.table.DefaultTableModel();

    model.addColumn("Appointment No");
    model.addColumn("Patient");
    model.addColumn("Dentist");
    model.addColumn("Treatment");
    model.addColumn("Time");
    model.addColumn("Status");

    while (scanner.hasNextLine()) {

        String line =
                scanner.nextLine();

        if (!line.trim().isEmpty()) {

            String[] data =
                    line.split("\\|");

            if (data.length == 6) {
                model.addRow(data);
            }
        }
    }

    scanner.close();

    tblReports.setModel(model);

} catch (Exception e) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Unable to load report."
    );

    e.printStackTrace();
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnAppointmentsByDateActionPerformed

    private void btnTreatmentSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreatmentSummaryActionPerformed
try {

    java.net.URL url =
            new java.net.URL(
                    "http://localhost:8080"
                    + "/api/reports/treatment-summary"
            );

    java.net.HttpURLConnection connection =
            (java.net.HttpURLConnection)
                    url.openConnection();

    connection.setRequestMethod("GET");

    java.util.Scanner scanner =
            new java.util.Scanner(
                    connection.getInputStream()
            );

    javax.swing.table.DefaultTableModel model =
            new javax.swing.table.DefaultTableModel();

    model.addColumn("Treatment Type");
    model.addColumn("Appointment Count");

    while (scanner.hasNextLine()) {

        String line =
                scanner.nextLine();

        if (!line.trim().isEmpty()) {

            String[] data =
                    line.split("\\|");

            if (data.length == 2) {
                model.addRow(data);
            }
        }
    }

    scanner.close();

    tblReports.setModel(model);

} catch (Exception e) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Unable to load report."
    );

    e.printStackTrace();
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnTreatmentSummaryActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
txtReportDate.setText("");

tblReports.setModel(
        new javax.swing.table.DefaultTableModel()
);        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
MainMenuForm mainMenu =
        new MainMenuForm();

mainMenu.setVisible(true);

this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReportsForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppointmentsByDate;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnTreatmentSummary;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblReports;
    private javax.swing.JTextField txtReportDate;
    // End of variables declaration//GEN-END:variables
}
